"""empty message

Revision ID: 4664bd227e20
Revises: 68ab0c5382ba
Create Date: 2021-07-22 01:01:07.743339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4664bd227e20'
down_revision = '68ab0c5382ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Barcode_table', sa.Column('brand_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'Barcode_table', 'User', ['user_id'], ['id'])
    op.drop_column('Barcode_table', 'by')
    op.drop_column('Barcode_table', 'img_ko')
    op.drop_column('Barcode_table', 'date_exit')
    op.drop_column('Barcode_table', 'date_entry')
    op.drop_column('Barcode_table', 'name_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Barcode_table', sa.Column('name_db', sa.VARCHAR(length=100), nullable=True))
    op.add_column('Barcode_table', sa.Column('date_entry', sa.DATETIME(), nullable=True))
    op.add_column('Barcode_table', sa.Column('date_exit', sa.DATETIME(), nullable=True))
    op.add_column('Barcode_table', sa.Column('img_ko', sa.BLOB(), nullable=True))
    op.add_column('Barcode_table', sa.Column('by', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'Barcode_table', type_='foreignkey')
    op.drop_column('Barcode_table', 'brand_name')
    # ### end Alembic commands ###
