"""empty message

Revision ID: 49d975c2fa6c
Revises: 905436a90a77
Create Date: 2021-07-12 19:01:57.018397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d975c2fa6c'
down_revision = '905436a90a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Barcode_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_no', sa.String(length=100), nullable=True),
    sa.Column('by', sa.String(length=100), nullable=True),
    sa.Column('name_db', sa.String(length=100), nullable=True),
    sa.Column('date_entry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_exit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('img_ko', sa.LargeBinary(), nullable=True),
    sa.Column('mimetype_db', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Barcode_table')
    # ### end Alembic commands ###
