"""empty message

Revision ID: 659f8ed57f2b
Revises: 9eb297186542
Create Date: 2021-07-20 23:32:31.991044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659f8ed57f2b'
down_revision = '9eb297186542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Barcode_table', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Barcode_table', type_='foreignkey')
    # ### end Alembic commands ###
