"""empty message

Revision ID: 8642846dee76
Revises: ef9c95cb7d57
Create Date: 2021-07-21 22:23:49.577313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8642846dee76'
down_revision = 'ef9c95cb7d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Barcode_table', sa.Column('item_name', sa.String(length=100), nullable=True))
    op.add_column('Barcode_table', sa.Column('serila_no', sa.String(length=100), nullable=True))
    op.add_column('Barcode_table', sa.Column('description', sa.String(length=100), nullable=True))
    op.add_column('Barcode_table', sa.Column('remarks', sa.String(length=400), nullable=True))
    op.add_column('Barcode_table', sa.Column('prod_pic', sa.LargeBinary(), nullable=True))
    op.add_column('Barcode_table', sa.Column('date_added', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'Barcode_table', 'User', ['user_id'], ['id'])
    op.drop_column('Barcode_table', 'by')
    op.drop_column('Barcode_table', 'name_db')
    op.drop_column('Barcode_table', 'date_exit')
    op.drop_column('Barcode_table', 'img_ko')
    op.drop_column('Barcode_table', 'date_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Barcode_table', sa.Column('date_entry', sa.DATETIME(), nullable=True))
    op.add_column('Barcode_table', sa.Column('img_ko', sa.BLOB(), nullable=True))
    op.add_column('Barcode_table', sa.Column('date_exit', sa.DATETIME(), nullable=True))
    op.add_column('Barcode_table', sa.Column('name_db', sa.VARCHAR(length=100), nullable=True))
    op.add_column('Barcode_table', sa.Column('by', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'Barcode_table', type_='foreignkey')
    op.drop_column('Barcode_table', 'date_added')
    op.drop_column('Barcode_table', 'prod_pic')
    op.drop_column('Barcode_table', 'remarks')
    op.drop_column('Barcode_table', 'description')
    op.drop_column('Barcode_table', 'serila_no')
    op.drop_column('Barcode_table', 'item_name')
    # ### end Alembic commands ###
