"""empty message

Revision ID: 9cf7b04c951c
Revises: 29b545c07e84
Create Date: 2021-07-20 23:14:50.958726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf7b04c951c'
down_revision = '29b545c07e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Barcode_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Barcode_table', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Barcode_table', type_='foreignkey')
    op.drop_column('Barcode_table', 'user_id')
    # ### end Alembic commands ###
