"""empty message

Revision ID: 9eb297186542
Revises: 9cf7b04c951c
Create Date: 2021-07-20 23:29:20.875327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb297186542'
down_revision = '9cf7b04c951c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Barcode_table', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Barcode_table', type_='foreignkey')
    # ### end Alembic commands ###
