"""empty message

Revision ID: eb5ef70e8294
Revises: 659f8ed57f2b
Create Date: 2021-07-20 23:35:28.787826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5ef70e8294'
down_revision = '659f8ed57f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Barcode_table', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Barcode_table', type_='foreignkey')
    # ### end Alembic commands ###
